name: Docker Image CI
on:
    push:
    branches: [ "mffllc" ]
    pull_request:
    branches: [ "mffllc" ]
    jobs: generate secret token
    build: javascript
    runs-on: ubuntu-latest
    steps: run
    uses: actions/checkout@v4
    name: Build the Docker image
    run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
